### ISSUE TITLE
Set up monitoring for counting downloading times for each dataset

### ISSUE THREAD

**Issue by olafveerman** [energy-data/energydata.info#57] opened 2016-12-12 15:11 UTC

**Comment by Naigege** [comment] 2018-04-25 22:48
Look into getting stats on:

downloads
which apps people browse to

**Comment by jodiegardiner** [comment] 2018-11-15 16:48
@shandaoz Is this still a relevant issue? This is a very vague specification.

**Comment by shandaoz** [comment] 2018-11-15 17:34
@jodiegardiner They meant to set-up a monitoring system to track the number of downloads each dataset has. We agreed to track downloads from now on from our earlier calls. 
Just to double check, we do have a mechanism to track dataset downloads now correct?

**Comment by jodiegardiner** [comment] 2018-11-15 18:06
No, that information is currently not tracked. Google Analytics doesn't do that by default so that requires development.

**Comment by shandaoz** [comment] 2018-11-15 18:09
I will discuss this with the team and see if we want to proceed with this :)

**Comment by jodiegardiner** [comment] 2019-09-06 10:06
duplicate of https://github.com/energy-data/energydata.info/issues/302

**Closed by jodiegardiner** 2019-09-06 10:06 UTC
