### ISSUE TITLE
Broken/strange cover images for applications and missing thumbnail icons

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#270] opened 2019-03-05 17:55 UTC
- Cover images on the ["Apps"](https://energydata.info/apps) page are either broken, distorted or blurred. 
- [Thumbnail icons](https://energydata.info/dataset/myanmar-cities-and-town-location-with-population) for data files are missing 
![image](https://user-images.githubusercontent.com/36420556/53826071-c0b6a780-3f45-11e9-914b-1e03c5943f7d.png)
![image](https://user-images.githubusercontent.com/36420556/53826085-cd3b0000-3f45-11e9-9637-d39c4e37b7a2.png)
![image](https://user-images.githubusercontent.com/36420556/53826029-a7adf680-3f45-11e9-8b46-25323d87ce30.png)

**Comment by jodiegardiner** [comment] 2019-03-06 17:39
investigating this one now. I suspect the images have become corrupted somehow.  This happened several months ago so this time rather than just fixing it by uploading replacements, I'll endeavour to see what the cause might be to prevent it occurring again in the future.

**Comment by jodiegardiner** [comment] 2019-03-07 14:58
this is fixed now

**Closed as completed by jodiegardiner** 2019-03-07 14:58 UTC
