### ISSUE TITLE
Unable to sign in on Staging 

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#276] opened 2019-04-29 15:05 UTC
The staging site does not allow me to sign back in as Editor/Administrator. 
![image](https://user-images.githubusercontent.com/36420556/56905638-93cad080-6a6e-11e9-8bd0-a25cebb75fc7.png)

**Comment by jodiegardiner** [comment] 2019-04-29 18:28
Hi @shandaoz 

I wiped the staging database today and replaced it with a copy from production (which happens every so often).

Could this be to blame?  If you have a test_account different to your admin one, you could create that on production too so that it will be copied over the next time I wipe staging.

If that is not what the problem is, get back to me and I'll investigate asap.

**Comment by shandaoz** [comment] 2019-04-29 18:32
Hi Jodie, 
The 404 Not Found Page appears the moment I click Login/Join. I did not have a chance to login in with my accounts :(

**Comment by jodiegardiner** [comment] 2019-04-30 09:39
Hi @shandaoz 

This is fixed now. You can once again login via the link in the menu.

**Closed as completed by jodiegardiner** 2019-04-30 09:39 UTC
