### ISSUE TITLE
New user invites

### ISSUE THREAD

**Issue by carderne** [energy-data/energydata.info#129] opened 2017-03-15 14:05 UTC
Related to #126, when I add a new user from the Organization management screen, they receive an email from `ckan.test.devseed@gmail.com`. This doesn't seem very professional and also was blocked by WBG spam catcher.

**Comment by olafveerman** [comment] 2017-03-16 13:58
Dupe of #34, which is now fixed.

**Closed by olafveerman** 2017-03-16 13:58 UTC
