### ISSUE TITLE
3E asked about update on the API issue 

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#289] opened 2019-08-20 13:50 UTC
David from 3E had questions about the API, below is quoted from David:

When I try to update files using the API with the python script provided, three problems occur:
•	A new file is created instead of updating the existing file with the same name;
•	The file itself is not available for download;
•	The file format and update date are unknown.
 
Some screenshots to clarify:
<image004.png>
 
The response that I get is the following:
{u'cache_last_updated': None,
u'cache_url': None,
u'created': u'2019-06-19T07:29:11.607134',
u'datastore_active': False,
u'description': u'',
u'format': u'',
u'hash': u'',
u'id': u'56fc53bb-7e14-40aa-b83e-80a93fe01bb0',
u'last_modified': None,
u'mimetype': None,
u'mimetype_inner': None,
u'name': u'Wind-Measurements_Nepal_Birtabesi_WB-ESMAP_Header.csv',
u'package_id': u'cd3f689a-7c04-4f7c-91c0-1037d033a872',
u'position': 32,
u'resource_type': None,
u'revision_id': u'd3e4142b-c84b-4064-8c3b-d5d4a3a789b1',
u'size': None,
u'state': u'active',
u'tilejson': u'False',
u'url': u'https://energydata.info/dataset/cd3f689a-7c04-4f7c-91c0-1037d033a872/resource/56fc53bb-7e14-40aa-b83e-80a93fe01bb0/download/___',
u'url_type': u'upload'}

**Comment by jodiegardiner** [comment] 2019-09-06 13:12
dupe of #301

**Closed as completed by jodiegardiner** 2019-09-06 13:12 UTC
